Created LandingPage Container,Routing for LandPage and Store was Provided
pranavakkian/CatalySTPocReact pull request #16
Opened 2020-12-02 16:32 UTC by kishore0079

2020-12-02 16:48 UTC, pranavakkian requested changes

2020-12-02 16:48 UTC, pranavakkian commented on package.json
> +    "react-test-renderer": "^17.0.1",
remove this

2020-12-02 16:48 UTC, pranavakkian commented on src/Components/LandingPage/index.jsx
> +  const display = `Welcome ${userName}`;
why this variable?

2020-12-02 16:48 UTC, pranavakkian commented on src/RootPath.js
> +const RootPath = '/';
rename this file constants.js OR routePaths.js because u will be adding all the paths in this file only.

2020-12-02 17:22 UTC, pranavakkian requested changes

2020-12-02 17:22 UTC, pranavakkian commented on src/Components/LandingPage/index.jsx
> +      <h1>{`Welcome ${userName}`}</h1>
```suggestion
      <h1>Welcome {userName}</h1>
```

2020-12-02 17:22 UTC, pranavakkian commented on src/Components/LandingPage/index.jsx
> +// import { Header } from 'semantic-ui-react';
Avoid comments.
```suggestion
```

2020-12-02 17:22 UTC, pranavakkian commented on src/Constants.js
> +const RootPath = '/';
keep this file inside a folder named constants

2020-12-03 05:39 UTC, pranavakkian approved these changes

2020-12-03 05:43 UTC, shivalibaghel7 approved these changes

2020-12-03 05:44 UTC, merged