Configured Jest and Enzyme
pranavakkian/CatalySTPocReact pull request #2
Opened 2020-11-26 18:20 UTC by P-1-X-3-L

2020-11-26 18:22 UTC, kishore0079 submitted a review, later dismissed

2020-11-26 18:43 UTC, pranavakkian requested changes

2020-11-26 18:43 UTC, pranavakkian commented on package.json
> +    "enzyme-adapter-react-16": "^1.15.5",
This is not going to work with react 17. Find out the appropriate version.

2020-11-26 18:43 UTC, pranavakkian commented on package.json
> +  "coverageReporters": ["text"]
This is not required. Instead add code coverage constraint. Find out on google on how to add global code coverage threshold on jest.
```suggestion
```

2020-11-26 18:43 UTC, pranavakkian commented on package.json
> +{"jest": {
keep this part after dev-dependencies. Also maintain proper indentation.

2020-11-26 19:10 UTC, shivalibaghel7 requested changes

2020-11-26 19:10 UTC, shivalibaghel7 commented on package.json
> +{"jest": {
Formatting is not proper.

2020-11-26 19:10 UTC, shivalibaghel7 commented on package.json
> +  "coverageReporters": ["text"]
For threshold, ensure 100% test coverage.

2020-11-27 03:28 UTC, pranavakkian requested changes

2020-11-27 03:28 UTC, pranavakkian commented on package.json
> +        "lines": 100
```suggestion
        "branches": 100,
        "functions": 100,
        "lines": 100,
        "statements": 100 
```

2020-11-27 07:38 UTC, shivalibaghel7 requested changes

2020-11-27 07:38 UTC, shivalibaghel7 commented on src/setupTests.js
>  // learn more: https://github.com/testing-library/jest-dom
Remove comments.

2020-11-27 07:42 UTC, pranavakkian submitted a review, later dismissed

2020-11-27 07:59 UTC, pranavakkian approved these changes

2020-11-27 07:59 UTC, shivalibaghel7 approved these changes

2020-11-27 08:15 UTC, kishore0079 approved these changes

2020-11-27 08:55 UTC, merged