Added Action for AddColleagueReducer
pranavakkian/CatalySTPocReact pull request #21
Opened 2020-12-03 14:16 UTC by P-1-X-3-L

2020-12-03 14:21 UTC, shivalibaghel7 approved these changes, later dismissed

2020-12-03 15:11 UTC, pranavakkian requested changes

2020-12-03 15:11 UTC, pranavakkian commented on src/Redux/Types.js
> +export const GET_COLLEAGUE_DATA = 'GET_COLLEAGUE_DATA';
```suggestion
export const SET_COLLEAGUE_DATA = 'SET_COLLEAGUE_DATA';
```

2020-12-03 15:11 UTC, pranavakkian commented on src/Redux/AddColleagueReducer/Action/index.js
> +  type: GET_COLLEAGUE_DATA,
```suggestion
  type: SET_COLLEAGUE_DATA,
```

2020-12-03 15:11 UTC, pranavakkian commented on src/Redux/AddColleagueReducer/Action/index.js
> +export const handleGetColleagueData = (value) => ({
```suggestion
export const handleSetColleagueData = (value) => ({
```

2020-12-03 15:20 UTC, pranavakkian approved these changes

2020-12-04 04:56 UTC, shivalibaghel7 approved these changes

2020-12-04 05:01 UTC, merged